# Generated by Django 4.0 on 2022-01-13 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.TextField()),
                ('mobile', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('pic', models.FileField(default='download.jpg', upload_to='profile')),
            ],
        ),
    ]
